# -*- coding: utf-8 -*-
"""task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vSEcN73jsiSyRQEH2QAMhvJziCy58RqF
"""

#IMPORT NECESSARY LIBRARIES
import pandas as pd
import numpy as np

#IMPORT THE DATASET
data = pd.read_csv("Unemployment in India.csv")
data

#HEAD OF THE DATA
data.head()

#TAIL OF THE DATA
data.tail()

#SHAPE OF TTHE DATASET
data.shape

#DETAILS ABOUT THE DATASET
data.info()

#DESCRIPTION OF THE DATASET
data.describe()

#PLOTTING A REGIONS IN X AXIS
x=data['Region']
x

#PLOTTING A ESTIMATED UNEMPLYMENT RATE IN Y AXIS
y = data[' Estimated Unemployment Rate (%)']
y

data1=data.iloc[:,3]
data1

#IMPORT THE LIBRARIES
import matplotlib.pyplot as plt
import plotly.express as px

#ANALYSING THE DATA BY BAR GRAPHS(state wise)
diagram = px.bar(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                 title = 'Unemployment Rate of State wise',template='plotly')
diagram.update_layout(xaxis={'categoryorder':'total descending'})
diagram.show()

#ANALYSING THE DATA BY BOX GRAPHS(State wise)
diagram = px.box(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                 title = 'Unemployment Rate of Region wise',template='plotly')
diagram.update_layout(xaxis={'categoryorder':'total descending'})
diagram.show()

#ANALYSING THE DATA BY HISTOGRAM
diagram = px.histogram(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                 title = 'Unemployment Rate of State wise',template='plotly')
diagram.update_layout(xaxis={'categoryorder':'total descending'})
diagram.show()